name: Daily Timestamp Update

on:
  schedule:
    - cron: '0 1 * * *'  # every day at 1 AM UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update timestamp in index.html
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M UTC")
          echo "Generated timestamp: $TIMESTAMP"
          sed -i "s|<!--LAST_UPDATED-->.*<!--END_LAST_UPDATED-->|<!--LAST_UPDATED--> $TIMESTAMP <!--END_LAST_UPDATED-->|" index.html

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "chore: update timestamp [$(date -u +"%Y-%m-%d %H:%M UTC")]" || echo "No changes to commit"
          git push
